FROM golang:1.23 AS build

WORKDIR /build

ENV GOTOOLCHAIN=auto

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG LDFLAGS
RUN CGO_ENABLED=0 go build \
    -ldflags "$LDFLAGS" \
    -o /calendar ./cmd/calendar

FROM alpine:3.18

RUN apk add --no-cache ca-certificates wget

COPY --from=build /calendar /usr/local/bin/calendar
COPY --from=build /build/configs/config.yaml /etc/calendar/config.yaml

CMD ["calendar", "-config", "/etc/calendar/config.yaml"]