apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.service.name }}
  labels:
    {{- include "calendar-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "calendar-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
